# NIVEL 1

# EJERCICIO 1 Peticions GET

In [1]:
# Instal·lació de requests (si cal)
# !pip install requests

import requests

BASE_URL = "https://jsonplaceholder.typicode.com"

## Obtenir publicacions (/posts)

In [2]:
posts_response = requests.get(f"{BASE_URL}/posts")

posts = posts_response.json()

print("Codi d'estat POSTS:", posts_response.status_code)
print("Quantitat de publicacions:", len(posts))

Codi d'estat POSTS: 200
Quantitat de publicacions: 100

## Obtenir usuaris (/users)

In [3]:
users_response = requests.get(f"{BASE_URL}/users")

users = users_response.json()

print("Codi d'estat USERS:", users_response.status_code)
print("Quantitat d'usuaris:", len(users))

Codi d'estat USERS: 200
Quantitat d'usuaris: 10

## Obtenir tasques (/todos)

In [4]:
todos_response = requests.get(f"{BASE_URL}/todos")

todos = todos_response.json()

print("Codi d'estat TODOS:", todos_response.status_code)
print("Quantitat de tasques:", len(todos))

Codi d'estat TODOS: 200
Quantitat de tasques: 200

# EJERCCIO 2. Mostrar quantitats totals i codis d'estat

In [5]:
print("===== RESUM =====")

print(f"POSTS -> Total: {len(posts)} | Status: {posts_response.status_code}")

print(f"USERS -> Total: {len(users)} | Status: {users_response.status_code}")

print(f"TODOS -> Total: {len(todos)} | Status: {todos_response.status_code}")

===== RESUM =====
POSTS -> Total: 100 | Status: 200
USERS -> Total: 10 | Status: 200
TODOS -> Total: 200 | Status: 200

# EJERCICIO 3. Petició a una publicació inexistent (error 404)

In [6]:
error_response = requests.get(f"{BASE_URL}/posts/999999")

print("Codi d'estat error:", error_response.status_code)

Codi d'estat error: 404

# EJERCICIO 4. Petició POST per crear una nova publicació

In [7]:
new_post = {
    "title": "La meva nova publicació",
    "body": "Aquest és el contingut de la publicació.",
    "userId": 1
}

post_response = requests.post(f"{BASE_URL}/posts", json=new_post)

print("Codi d'estat POST:", post_response.status_code)

print("Resposta JSON:")
print(post_response.json())

Codi d'estat POST: 201
Resposta JSON:
{'title': 'La meva nova publicació', 'body': 'Aquest és el contingut de la publicació.', 'userId': 1, 'id': 101}

# EJERCICIO 5. Petició PATCH per modificar parcialment una publicació

In [8]:
update_data = {
    "title": "Títol modificat"
}

patch_response = requests.patch(
    f"{BASE_URL}/posts/1",
    json=update_data
)

print("Codi d'estat PATCH:", patch_response.status_code)

print("Resposta JSON:")
print(patch_response.json())

Codi d'estat PATCH: 200
Resposta JSON:
{'userId': 1, 'id': 1, 'title': 'Títol modificat', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

# EJERCICIO 3. Petició DELETE sobre una publicació

In [9]:
delete_response = requests.delete(f"{BASE_URL}/posts/1")

print("Codi d'estat DELETE:", delete_response.status_code)

print("Resposta JSON:")
print(delete_response.json())

Codi d'estat DELETE: 200
Resposta JSON:
{}

# NIVEL 2

# EJERCICIO 1

https://restcountries.com/

Esta API permite obtener información sobre países mediante peticiones GET.

# EJERCICIO 2. Documentación de la API

## Endpoints disponibles

GET /v3.1/all
→ Devuelve información de todos los países.

GET /v3.1/name/{name}
→ Busca países por nombre.

## Parámetros y filtros interesantes

fields=
→ Permite seleccionar únicamente algunos campos.

Ejemplo:
https://restcountries.com/v3.1/all?fields=name,capital,population

region=
→ Permite filtrar por región.

Ejemplo:
https://restcountries.com/v3.1/region/europe

## Formato de respuesta

La API devuelve las respuestas en formato JSON.

# EJERCICIO 3. Petición GET sencilla

## Importar librerías

In [10]:
import requests
import pandas as pd

## Hacer petición GET

In [11]:
url = "https://restcountries.com/v3.1/all?fields=name,capital,population,region"

response = requests.get(url)

print("Código de estado:", response.status_code)

Código de estado: 200

## Convertir respuesta JSON

In [12]:
countries = response.json()

print("Cantidad de países:", len(countries))

Cantidad de países: 250

## Mostrar algunos campos del JSON

In [13]:
for country in countries[:5]:

    print("País:", country["name"]["common"])

    capital = country.get("capital", ["Sin capital registrada"])[0]

    print("Capital:", capital)

    print("Población:", country.get("population"))

    print("-" * 40)

País: Anguilla
Capital: The Valley
Población: 16010
----------------------------------------
País: Guatemala
Capital: Guatemala City
Población: 18079810
----------------------------------------
País: Gambia
Capital: Banjul
Población: 2422712
----------------------------------------
País: Mexico
Capital: Mexico City
Población: 130575786
----------------------------------------
País: Malawi
Capital: Lilongwe
Población: 20734262
----------------------------------------

# EJERCICIO 4. Convertir datos a DataFrame de pandas

## Crear lista con datos simplificados

In [14]:
import pandas as pd

data = []

for country in countries:

    capitales = country.get("capital", [])

    capital = capitales[0] if len(capitales) > 0 else "Sin capital"

    data.append({
        "Pais": country["name"]["common"],
        "Capital": capital,
        "Poblacion": country.get("population"),
        "Region": country.get("region")
    })

## Crear DataFrame

In [15]:
df = pd.DataFrame(data)

## Mostrar primeras filas

In [16]:
df.head()

        Pais         Capital  Poblacion    Region
0   Anguilla      The Valley      16010  Americas
1  Guatemala  Guatemala City   18079810  Americas
2     Gambia          Banjul    2422712    Africa
3     Mexico     Mexico City  130575786  Americas
4     Malawi        Lilongwe   20734262    Africa

# NIVEL 3

# EJERCICIO 1. Buscar un dataset con package_search

## Importar librerías

In [17]:
import requests
import pandas as pd

## URL base de la API

In [18]:
BASE_URL = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

## Buscar datasets relacionados con "bicing"

In [19]:
search_url = f"{BASE_URL}/package_search"

params = {
    "q": "bicing"
}

response = requests.get(search_url, params=params)

print("Código de estado:", response.status_code)

Código de estado: 200

## Convertir respuesta a JSON

In [20]:
data = response.json()

## Mostrar algunos resultados encontrados

In [21]:
results = data["result"]["results"]

print("Cantidad de datasets encontrados:", len(results))

for dataset in results[:3]:
    print("Título:", dataset["title"])
    print("ID:", dataset["id"])
    print("-" * 50)

Cantidad de datasets encontrados: 5
Título: New Bicing stations status of Barcelona city
ID: 6aa3416d-ce1a-494d-861b-7bd07f069600
--------------------------------------------------
Título: New Bicing stations information of the city of Barcelona
ID: bd2462df-6e1e-4e37-8205-a4b8e7313b84
--------------------------------------------------
Título: Bicing service use of the city of Barcelona from August 2018 to March 2019
ID: 4a469cf6-dbab-4aa1-b492-aa0af9af93c9
--------------------------------------------------

# EJERCICIO 2. Obtener detalles del dataset con package_show

## Seleccionamos el primer dataset encontrado.

In [22]:
dataset_id = results[0]["id"]

show_url = f"{BASE_URL}/package_show"

params = {
    "id": dataset_id
}

response_show = requests.get(show_url, params=params)

print("Código de estado:", response_show.status_code)

Código de estado: 200

## Ver recursos disponibles

In [23]:
dataset_info = response_show.json()

resources = dataset_info["result"]["resources"]

for resource in resources:
    print("Nombre:", resource["name"])
    print("Formato:", resource["format"])
    print("Resource ID:", resource["id"])
    print("-" * 50)

Nombre: Estat_Estacions_Bicing_securitzat_json
Formato: JSON
Resource ID: 1b215493-9e63-4a12-8980-2d7e0fa19f85
--------------------------------------------------
Nombre: 2026_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 28627d99-7c79-4eb5-bb30-2ef5016cf85e
--------------------------------------------------
Nombre: 2026_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 455a4db8-21ee-44e5-989b-12284e69cb86
--------------------------------------------------
Nombre: 2026_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: aa833a84-e434-4139-a578-deffd73a592a
--------------------------------------------------
Nombre: 2025_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 6bfc06e2-ad96-4059-a57d-ce9334452c0f
--------------------------------------------------
Nombre: 2025_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: af6f7cc4-3193-4b35-8e30-38f95df921cf
--------------------------------------------------
Nombre: 2025_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 0e904458-8d7a-42ac-b7c2-e41627a4577c
--------------------------------------------------
Nombre: 2025_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 885bbac5-a0d8-425e-919a-a4a855808785
--------------------------------------------------
Nombre: 2025_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: c14e7b54-87c8-4ea8-aa1a-a8b5828989fe
--------------------------------------------------
Nombre: 2025_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 1b47f8e6-db40-4835-8d65-7f4349efb8f5
--------------------------------------------------
Nombre: 2025_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: aba91b60-68f1-4a79-ba6b-c3ac87dc8c4e
--------------------------------------------------
Nombre: 2025_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 02d2975f-ce3c-4215-b1b2-eb6a2b4d019e
--------------------------------------------------
Nombre: 2025_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: fb3e741b-299b-487d-98b4-11a8eb0634d1
--------------------------------------------------
Nombre: 2025_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: efcfa487-708e-4766-aa2c-5d63451d11b2
--------------------------------------------------
Nombre: 2025_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: fe880433-8468-4e85-a851-31036ab86af9
--------------------------------------------------
Nombre: 2024_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 229fdebf-daa8-4f22-9b0c-cf03ab0279ca
--------------------------------------------------
Nombre: 2024_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: f482f76c-0aed-4c06-9abd-f90b3ea64d69
--------------------------------------------------
Nombre: 2024_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 869e5799-621d-497d-8364-1cb23b718da2
--------------------------------------------------
Nombre: 2024_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 03816585-7818-41ca-bc18-fdf56f839fb6
--------------------------------------------------
Nombre: 2024_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: f8d0e63f-1c89-4bfc-bfe2-c180bdfbba70
--------------------------------------------------
Nombre: 2024_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e69daa68-0096-43e8-8e69-8219b9a13a4c
--------------------------------------------------
Nombre: 2024_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: dc17e68c-6faf-4210-b93c-864e993e9d70
--------------------------------------------------
Nombre: 2024_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: f0043c1f-38db-4e34-aaf8-8cd71174613b
--------------------------------------------------
Nombre: 2024_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 727dbd48-9348-4f43-a672-b79f73f1f8af
--------------------------------------------------
Nombre: 2024_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e5ed1e52-b205-49ff-b99c-a2307a8ce9a3
--------------------------------------------------
Nombre: 2024_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: dec7d860-dcb9-46ac-b241-4d7e711c39d6
--------------------------------------------------
Nombre: 2024_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 29b46066-dc16-422d-85dd-6799baa7e839
--------------------------------------------------
Nombre: 2023_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 1ba8d8c4-c13b-47a8-b08f-19eba4266efc
--------------------------------------------------
Nombre: 2023_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 84c0d6e5-9011-40c2-80a7-65d9af4f671f
--------------------------------------------------
Nombre: 2023_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: baba6358-6554-4629-877d-a82fd3925ed7
--------------------------------------------------
Nombre: 2023_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 5f8d4611-6125-4ce3-82fd-39c83f0e74bb
--------------------------------------------------
Nombre: 2023_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 829cce55-a081-48bf-9744-c61ea26073cc
--------------------------------------------------
Nombre: 2023_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: f6bc68df-88a0-4e69-b513-dbbd941eea17
--------------------------------------------------
Nombre: 2023_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 4e75cb2a-7b6d-4f73-8ce6-be52de54d46c
--------------------------------------------------
Nombre: 2023_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e883bca2-d274-4eb5-8830-d75b080d34b3
--------------------------------------------------
Nombre: 2023_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 600f1b07-4af2-4fbb-b6d0-a473e3426d24
--------------------------------------------------
Nombre: 2023_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: d41a1b34-503a-4e32-afc9-1850f74a2e3b
--------------------------------------------------
Nombre: 2023_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 813ab563-358b-4dd5-b41c-816bf3927763
--------------------------------------------------
Nombre: 2023_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 42e1d85c-86e3-4122-b1b3-de0f7fcf01fa
--------------------------------------------------
Nombre: 2022_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e13eda87-14c3-4589-9ff9-d721c3fa4dbb
--------------------------------------------------
Nombre: 2022_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 2e423344-cc5b-4c96-95e4-3f47bf29f089
--------------------------------------------------
Nombre: 2022_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: f2b7e984-bb83-495d-b103-6e67631eb837
--------------------------------------------------
Nombre: 2022_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 72f96ab8-f8ae-46d8-8f4d-85220daff9fa
--------------------------------------------------
Nombre: 2022_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: c35e536e-256d-4ab4-afe0-62e9034f5159
--------------------------------------------------
Nombre: 2022_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 697dbea2-eee2-4679-9dc4-100115c8d45a
--------------------------------------------------
Nombre: 2022_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 5a74d097-6a31-421a-9493-3f67de18787c
--------------------------------------------------
Nombre: 2022_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 65490e4c-e33f-4320-9542-90058f0a6b37
--------------------------------------------------
Nombre: 2022_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 2e41fee1-5267-4ec7-9553-56dbe8a454e7
--------------------------------------------------
Nombre: 2022_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 6e3337af-b6c1-47b4-9deb-58d86802f00a
--------------------------------------------------
Nombre: 2022_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 23b53daa-5db1-434b-b68d-3f18981f1b90
--------------------------------------------------
Nombre: 2022_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: ed6e7971-79f4-422d-b0d9-8208369acb77
--------------------------------------------------
Nombre: 2021_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 081b0be9-246a-4f7a-bfc6-47682b27d88b
--------------------------------------------------
Nombre: 2021_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: d0fc5c39-8017-4812-b3ea-9c200a89b1b3
--------------------------------------------------
Nombre: 2021_03_Març_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 7fe6be55-75dd-4270-bcbf-a97f9a8dc0a3
--------------------------------------------------
Nombre: 2021_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e05e26c9-b8a2-4838-b673-61b85e30564e
--------------------------------------------------
Nombre: 2021_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 3cc4e750-bab8-48e4-9a96-3224153b36d7
--------------------------------------------------
Nombre: 2021_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 72e91d78-70bf-4949-9b24-3dc0fd238ae1
--------------------------------------------------
Nombre: 2021_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 23cc51a0-382a-4b83-835b-b5f0da6614f0
--------------------------------------------------
Nombre: 2021_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: c100cd3f-72b9-4a73-a8c4-bbbe592d72a9
--------------------------------------------------
Nombre: 2021_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: b5cf7ec2-334d-492c-84fa-23fbfa931d25
--------------------------------------------------
Nombre: 2021_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: e483b331-98cc-495d-85a9-8916419e3e6b
--------------------------------------------------
Nombre: 2021_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: a87195e3-0819-43db-a43c-caa90327c68d
--------------------------------------------------
Nombre: 2021_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 1670e154-58dc-44e1-8138-8a167ef580ca
--------------------------------------------------
Nombre: 2020_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 138d7095-8d8e-4c0e-ac1a-9a280bf08083
--------------------------------------------------
Nombre: 2020_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 71325945-95f0-4af5-ae01-ccf8be4781a1
--------------------------------------------------
Nombre: 2020_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: d229bf51-efe6-48b4-9192-40abda5caf19
--------------------------------------------------
Nombre: 2020_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: c5468d46-6cf4-4f1e-b7ad-d91292be830b
--------------------------------------------------
Nombre: 2020_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 6c03e39a-ca8f-451d-b8f3-c63cc56c23c4
--------------------------------------------------
Nombre: 2020_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 16fbdedf-a150-4309-853d-f99cb2404a20
--------------------------------------------------
Nombre: 2020_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 9223b338-b8b3-427e-b1b4-b4dd14fd9586
--------------------------------------------------
Nombre: 2020_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 7970ad81-792b-45c6-888d-7f0e36f144b9
--------------------------------------------------
Nombre: 2020_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: d9b34297-99b2-4cca-97c9-2ce7780289b4
--------------------------------------------------
Nombre: 2020_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 79aed163-0b24-498e-b8c0-a0ddbb0fb2b5
--------------------------------------------------
Nombre: 2020_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 3e9ba621-c2b0-4330-ae0d-092addc7afef
--------------------------------------------------
Nombre: 2020_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: d33263e1-1be2-4ff1-98ef-395e8a56944a
--------------------------------------------------
Nombre: 2019_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 6524ae13-bba4-4d83-b9d7-fbf679e64d10
--------------------------------------------------
Nombre: 2019_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 428adbdd-96f4-4b21-acb1-caab41fbdff4
--------------------------------------------------
Nombre: 2019_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 7d9400a5-fcd8-4b16-994e-9f117186fe87
--------------------------------------------------
Nombre: 2019_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 6265796f-2cda-43c6-b34c-082c1af02397
--------------------------------------------------
Nombre: 2019_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: bb374609-3e63-47a0-b821-0fd01f025eaa
--------------------------------------------------
Nombre: 2019_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 7e234590-739d-4a13-be8c-90bc1be23ce1
--------------------------------------------------
Nombre: 2019_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 489d3e22-9cb4-42c9-812d-60c98d54324a
--------------------------------------------------
Nombre: 2019_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 743a5277-8f1f-4515-9de2-9f6ce20895b6
--------------------------------------------------
Nombre: 2019_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: c6ad9c8c-c365-44bc-a420-1ee32f788251
--------------------------------------------------
Nombre: 2019_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
Resource ID: 29ef34c6-1dde-49c8-a636-28a51ba647fe
--------------------------------------------------

# EJERCICIO 3. Usar datastore_search para recuperar 100 registros

## Seleccionamos un recurso en formato CSV o JSON.

In [24]:
resource_id = resources[0]["id"]

datastore_url = f"{BASE_URL}/package_show"

## Obtener URL del recurso

In [25]:
resource_url = resources[0]["url"]

print(resource_url)

https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1b215493-9e63-4a12-8980-2d7e0fa19f85/download

## Leer datos con pandas

In [26]:
df = pd.read_csv(
    resource_url,
    sep=";",
    encoding="utf-8",
    on_bad_lines="skip"
)

## Mostrar al menos 100 registros

In [27]:
df_100 = df.head(100)

df_100

                                      <!DOCTYPE html>
0   <html lang="ca" dir="ltr" prefix="content: htt...
1                                              <head>
2     <link rel="profile" href="http://www.w3.org/...
3                              <meta charset="utf-8">
4     <meta name="viewport" content="width=device-...
..                                                ...
95                  <button type="button" id="bcnb...
96                    <span class="bcnbrand-icon i...
97                                          </button>
98                  <button type="submit" aria-lab...
99                    <span class="bcnbrand-icon i...

[100 rows x 1 columns]

# EJERCICIO 4. Convertir resultados a DataFrame

## Mostrar primeras filas

In [28]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [29]:
df.head()

                                     <!DOCTYPE html>
0  <html lang="ca" dir="ltr" prefix="content: htt...
1                                             <head>
2    <link rel="profile" href="http://www.w3.org/...
3                             <meta charset="utf-8">
4    <meta name="viewport" content="width=device-...

# EJERCICIO 5. Guardar el DataFrame en CSV

In [30]:
df_100.to_csv("bicing_barcelona.csv", index=False)

print("Archivo CSV guardado correctamente")

Archivo CSV guardado correctamente